type Subscription {
  postAdded: Post
}

type Query {
  posts: [Post]
}

type Mutation {
  addPost(author: String, comment: String): Post
}

type Post {
  id: String
  author: String
  comment: String
  time: String
}
